
version: '3'

services:
  server:
    # build: ./server
    # To replace with the correct path of your server image
    image: wildcarbon/wns-deploy-server
    command: sh -c "npm run build && npm run prod"
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
    depends_on:
      - mongodb
  client:
    # build: ./client
    # To replace with the correct path of your client image
    image: wildcarbon/wns-deploy-client
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production  
  mongodb:
    image: mongo:4.4.9
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build: